### PR TITLE
Alternate names for exercises

### LINKED ISSUE #3: Alternate names for exercises
Thanks for this really helpful project!

I am trying to port a workout dump that uses exercises from [ExerciseDB](https://rapidapi.com/justin-WFnsXH_t6/api/exercisedb/). Since most of the exercises have a different name here, it is quite difficult to do so. I suggest we add a new key to each exercise called `alternateNames: string[]`. This will allow others users to port their own data to this dataset more easily.

I can make a PR for the same.

### PR DESCRIPTION
**Pull request by IgnisDa**
Fixes #3.

### CODE REVIEW

**Comment by yuhonas** [comment]
Hey @IgnisDa looks like the `dist/exercises.json` [is out of date](https://github.com/yuhonas/free-exercise-db/actions/runs/5822606263/job/15787596559?pr=6), can you commit an updated version using `make dist/exercises.json` as you've added the new alternative names, also out of interest have you added any alternative names or just the schema/potential for it? it's a big commit so it's difficult to tell

**Comment by IgnisDa** [comment]
I haven't added alternate names for around 5 exercises 😅. It is pretty difficult to reconcile differences.

**Comment by IgnisDa** [comment]
If you want, I can send you the exercisedb dataset and you can help me too?

**Comment by yuhonas** [comment]
> If you want, I can send you the exercisedb dataset and you can help me too?

Sure send them over @IgnisDa I can take a look

**Comment by IgnisDa** [comment]
It's a 300mb dataset. How do I send it to you?

**Pull request closed without merging**
